version: "3.8"

services:
  redis:
    image: redis:7-alpine
    hostname: redis
    command: redis-server --appendonly yes
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - chatwoot_net

  postgres:
    image: pgvector/pgvector:pg16
    hostname: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Mfcd62!!Mfcd62!!"
      POSTGRES_DB: chatwoot
      TZ: America/Sao_Paulo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chatwoot_net

  chatwoot_app:
    image: localhost/chatwoot-custom:latest
    hostname: chatwoot_app
    entrypoint: docker/entrypoints/rails.sh
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"
    volumes:
      - chatwoot_data:/app/storage
    environment:
      INSTALLATION_NAME: Chatwoot
      NODE_ENV: production
      RAILS_ENV: production
      INSTALLATION_ENV: docker
      SECRET_KEY_BASE: O9j4yD2QLf2Ea0kLTxLymtojVvefem9oCigtCo3YK0N0xeMRP0Skcbwi7yOO
      FRONTEND_URL: http://172.26.236.22:3000
      DEFAULT_LOCALE: pt_BR
      FORCE_SSL: "enable"
      ENABLE_ACCOUNT_SIGNUP: "true"
      REDIS_URL: redis://redis:6379
      POSTGRES_HOST: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: "Mfcd62!!Mfcd62!!"
      POSTGRES_DATABASE: chatwoot
      ACTIVE_STORAGE_SERVICE: local
      RAILS_LOG_TO_STDOUT: "true"
      USE_INBOX_AVATAR_FOR_BOT: "true"
      SIDEKIQ_CONCURRENCY: "10"
      RACK_TIMEOUT_SERVICE_TIMEOUT: "0"
      RAILS_MAX_THREADS: "5"
      WEB_CONCURRENCY: "2"
      ENABLE_RACK_ATTACK: "false"
      WEBHOOKS_TRIGGER_TIMEOUT: "40"
      MAILER_SENDER_EMAIL: chat@penhacontabilidade.com.br
      SMTP_ADDRESS: mail.penhacontabilidade.com.br
      SMTP_PORT: 465
      SMTP_USERNAME: chat@penhacontabilidade.com.br
      SMTP_PASSWORD: penha@7623
      SMTP_AUTHENTICATION: login
      SMTP_DOMAIN: penhacontabilidade.com.br
      SMTP_ENABLE_STARTTLS_AUTO: true
      SMTP_TLS: true
    networks:
      - chatwoot_net

  chatwoot_sidekiq:
    image: localhost/chatwoot-custom:latest
    hostname: chatwoot_sidekiq
    entrypoint: docker/entrypoints/rails.sh
    command: bundle exec sidekiq -C config/sidekiq.yml
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    volumes:
      - chatwoot_data:/app/storage
    environment:
      INSTALLATION_NAME: Chatwoot
      NODE_ENV: production
      RAILS_ENV: production
      INSTALLATION_ENV: docker
      SECRET_KEY_BASE: O9j4yD2QLf2Ea0kLTxLymtojVvefem9oCigtCo3YK0N0xeMRP0Skcbwi7yOO
      FRONTEND_URL: http://172.26.236.22:3000
      DEFAULT_LOCALE: pt_BR
      FORCE_SSL: "enable"
      ENABLE_ACCOUNT_SIGNUP: "true"
      REDIS_URL: redis://redis:6379
      POSTGRES_HOST: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: "Mfcd62!!Mfcd62!!"
      POSTGRES_DATABASE: chatwoot
      ACTIVE_STORAGE_SERVICE: local
      RAILS_LOG_TO_STDOUT: "true"
      USE_INBOX_AVATAR_FOR_BOT: "true"
      SIDEKIQ_CONCURRENCY: "10"
      RACK_TIMEOUT_SERVICE_TIMEOUT: "0"
      RAILS_MAX_THREADS: "5"
      WEB_CONCURRENCY: "2"
      ENABLE_RACK_ATTACK: "false"
      WEBHOOKS_TRIGGER_TIMEOUT: "40"
      MAILER_SENDER_EMAIL: chat@penhacontabilidade.com.br
      SMTP_ADDRESS: mail.penhacontabilidade.com.br
      SMTP_PORT: 465
      SMTP_USERNAME: chat@penhacontabilidade.com.br
      SMTP_PASSWORD: penha@7623
      SMTP_AUTHENTICATION: login
      SMTP_DOMAIN: penhacontabilidade.com.br
      SMTP_ENABLE_STARTTLS_AUTO: true
      SMTP_TLS: true
    networks:
      - chatwoot_net

volumes:
  redis_data:
  postgres_data:
  chatwoot_data:

networks:
  chatwoot_net:
    driver: bridge
